# Generated by Django 2.2.1 on 2019-05-21 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
