# Generated by Django 2.2.1 on 2019-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190521_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=100, unique=True),
        ),
    ]
